import React,{useCallback,useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{z}from"zod";
import"./style.css";

const windowSchema=z.object({presence:z.string(),used_percent:z.number(),reset_at:z.number(),reset_after_seconds:z.number(),limit_window_seconds:z.number(),used_tokens:z.number(),remaining_tokens:z.number(),limit_tokens:z.number()});
const accountSchema=z.object({Key:z.string(),ID:z.string(),AuthIndex:z.string(),Label:z.string(),Plan:z.string(),Snapshot:z.object({primary:windowSchema,secondary:windowSchema,eligible:z.boolean(),reason:z.string(),cycle_id:z.string()}),diagnostic:z.string().optional()});
const accountsSchema=z.object({data:z.array(accountSchema)});const statusSchema=z.object({enabled:z.boolean(),auto_activate:z.boolean(),scan_interval:z.string(),last_scan:z.string(),last_error:z.string()});
const runSchema=z.object({id:z.number(),Mode:z.string(),StartedAt:z.string(),FinishedAt:z.string(),Scanned:z.number(),Eligible:z.number(),Verified:z.number(),Skipped:z.number(),Failed:z.number(),Partial:z.number()});const runsSchema=z.object({data:z.array(runSchema)});
const managementSessionSchema=z.object({type:z.literal("cliproxy:management-session"),version:z.literal(1),managementKey:z.string().min(1)});
type Account=z.infer<typeof accountSchema>;type QuotaWindow=z.infer<typeof windowSchema>;type Status=z.infer<typeof statusSchema>;type Run=z.infer<typeof runSchema>;
const copy={pt:{title:"Quota do Codex",subtitle:"Janelas, reinícios e ativações por conta.",overview:"Visão geral",accounts:"Contas",history:"Últimas varreduras",auto:"Ativação automática",on:"Ativa",off:"Desativada",last:"Última varredura",interval:"Intervalo",next:"Próximo reset",active:"Em uso",eligible:"Elegível",unknown:"Indisponível",primary:"Janela principal",secondary:"Janela secundária",used:"usado",remaining:"restante",reset:"reinicia em",scan:"Verificar agora",prepare:"Preparar ativação",confirm:"Confirmar ativação",cancel:"Cancelar",selected:"contas selecionadas",warning:"A ativação envia uma requisição mínima e não pode ser desfeita.",empty:"Nenhuma conta Codex válida encontrada.",key:"Chave de management",connect:"Abrir painel",connecting:"Conectando ao Management Center…",sessionUnavailable:"A sessão do Management Center não pôde ser compartilhada. Atualize o painel e tente novamente.",retry:"Tentar novamente",badKey:"Não foi possível autenticar ou carregar as quotas.",scanned:"verificadas",verified:"ativadas",skipped:"ignoradas",failed:"falhas",mode:"modo",refresh:"Atualizar",reason:{window_already_active:"Ciclo já está ativo",no_fresh_window:"Nenhuma janela recém-aberta",window_missing:"Janela ausente",ambiguous_window:"Estado de quota ambíguo"}},en:{title:"Codex quota",subtitle:"Account windows, resets, and activations.",overview:"Overview",accounts:"Accounts",history:"Recent scans",auto:"Automatic activation",on:"On",off:"Off",last:"Last scan",interval:"Interval",next:"Next reset",active:"In use",eligible:"Eligible",unknown:"Unavailable",primary:"Primary window",secondary:"Secondary window",used:"used",remaining:"remaining",reset:"resets in",scan:"Check now",prepare:"Prepare activation",confirm:"Confirm activation",cancel:"Cancel",selected:"selected accounts",warning:"Activation sends one minimal request and cannot be undone.",empty:"No valid Codex account found.",key:"Management key",connect:"Open panel",connecting:"Connecting to Management Center…",sessionUnavailable:"The Management Center session could not be shared. Refresh the panel and try again.",retry:"Try again",badKey:"Could not authenticate or load quotas.",scanned:"scanned",verified:"activated",skipped:"skipped",failed:"failed",mode:"mode",refresh:"Refresh",reason:{window_already_active:"Cycle is already active",no_fresh_window:"No newly opened window",window_missing:"Window is absent",ambiguous_window:"Ambiguous quota state"}}}as const;
function duration(seconds:number){if(seconds<=0)return"—";const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);if(days)return`${days}d ${hours}h`;if(hours)return`${hours}h ${minutes}m`;return`${Math.max(1,minutes)}m`}
function date(value:string){if(!value)return"—";const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?"—":new Intl.DateTimeFormat(undefined,{dateStyle:"short",timeStyle:"short"}).format(parsed)}
function identity(account:Account){return account.Label||account.ID||account.AuthIndex||"Codex"}

function App(){
 const[lang,setLang]=useState<"pt"|"en">(()=>navigator.language.toLowerCase().startsWith("pt")?"pt":"en");const t=copy[lang];
 const embedded=window.parent!==window;const[key,setKey]=useState(()=>embedded?"":sessionStorage.getItem("quota-management-key")??"");const[draft,setDraft]=useState(key);const[bridgeFailed,setBridgeFailed]=useState(false);const[accounts,setAccounts]=useState<Account[]>([]);const[status,setStatus]=useState<Status|null>(null);const[runs,setRuns]=useState<Run[]>([]);const[selected,setSelected]=useState<string[]>([]);const[token,setToken]=useState("");const[error,setError]=useState("");const[loading,setLoading]=useState(false);
 const api=useCallback(async(path:string,method="GET",body?:unknown)=>{const response=await fetch(`/v0/management/plugins/codex-quota-activation/${path}`,{method,headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body),cache:"no-store"});if(!response.ok)throw new Error(String(response.status));return response.json()as Promise<unknown>},[key]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const[a,b,c]=await Promise.all([api("accounts"),api("status"),api("runs")]);const parsed=accountsSchema.parse(a);setAccounts(parsed.data);setStatus(statusSchema.parse(b));setRuns(runsSchema.parse(c).data.slice(0,6));setSelected(current=>current.filter(item=>parsed.data.some(account=>account.Key===item&&account.Snapshot.eligible)))}catch{setError(t.badKey)}finally{setLoading(false)}},[api,t.badKey]);
 useEffect(()=>{if(key)void load()},[key,load]);function connect(){const clean=draft.trim();sessionStorage.setItem("quota-management-key",clean);setKey(clean)}
 useEffect(()=>{if(!embedded)return;sessionStorage.removeItem("quota-management-key");const request=()=>window.parent.postMessage({type:"cliproxy:management-session-request",version:1},window.location.origin);const receive=(event:MessageEvent<unknown>)=>{if(event.origin!==window.location.origin||event.source!==window.parent)return;const parsed=managementSessionSchema.safeParse(event.data);if(!parsed.success)return;setBridgeFailed(false);setKey(parsed.data.managementKey)};window.addEventListener("message",receive);request();const timeout=window.setTimeout(()=>setBridgeFailed(true),3000);return()=>{window.clearTimeout(timeout);window.removeEventListener("message",receive)}},[embedded]);
 async function scan(){setLoading(true);setError("");try{await api("scan","POST");await load()}catch{setError(t.badKey);setLoading(false)}}async function preview(){setLoading(true);setError("");try{const raw=await api("preview","POST",{accounts:selected});setToken(z.object({confirmation_token:z.string()}).parse(raw).confirmation_token)}catch{setError(t.badKey)}finally{setLoading(false)}}async function run(){setLoading(true);setError("");try{await api("run","POST",{confirmation_token:token});setToken("");setSelected([]);await load()}catch{setError(t.badKey);setLoading(false)}}
 const eligible=accounts.filter(account=>account.Snapshot.eligible).length;const nextReset=useMemo(()=>{const times=accounts.flatMap(account=>[account.Snapshot.primary,account.Snapshot.secondary]).filter(window=>window.presence==="present"&&window.reset_after_seconds>0).map(window=>window.reset_after_seconds);return times.length?Math.min(...times):0},[accounts]);
 if(!key&&embedded)return <SessionState title={t.title}message={bridgeFailed?t.sessionUnavailable:t.connecting}action={bridgeFailed?t.retry:""}onRetry={()=>{setBridgeFailed(false);window.parent.postMessage({type:"cliproxy:management-session-request",version:1},window.location.origin)}}/>;
 if(!key)return <Login title={t.title}subtitle={t.subtitle}label={t.key}action={t.connect}value={draft}onChange={setDraft}onSubmit={connect}/>;
 return <main className="app-shell"><header className="page-header"><div><div className="crumb">CLIProxyAPI <span>/</span> {t.title}</div><h1>{t.title}</h1><p>{t.subtitle}</p></div><div className="header-actions"><select value={lang}onChange={event=>setLang(event.target.value as"pt"|"en")}><option value="pt">PT-BR</option><option value="en">EN</option></select><button className="quiet"onClick={()=>void scan()}>↻ {t.scan}</button></div></header>{loading&&<div className="progress"/>}{error&&<div className="notice error">{error}</div>}
 <section className="overview"><div className="section-heading"><div className="section-kicker">{t.overview}</div></div><div className="summary-grid"><Summary label={t.auto}value={status?.auto_activate?t.on:t.off}status={status?.auto_activate?"good":"neutral"}/><Summary label={t.accounts}value={String(accounts.length)}detail={`${eligible} ${t.eligible.toLowerCase()}`}/><Summary label={t.next}value={duration(nextReset)}/><Summary label={t.interval}value={status?.scan_interval??"—"}/><Summary label={t.last}value={date(status?.last_scan??"")}/></div></section>
 <section className="accounts-section"><div className="section-heading"><div><div className="section-kicker">{t.accounts}</div><h2>{accounts.length} Codex OAuth</h2></div><span>{eligible} {t.eligible.toLowerCase()}</span></div>{accounts.length?<div className="accounts">{accounts.map(account=><AccountRow key={account.Key}account={account}selected={selected.includes(account.Key)}onSelect={checked=>setSelected(current=>checked?[...new Set([...current,account.Key])]:current.filter(item=>item!==account.Key))}labels={t}/>)}</div>:!loading&&<div className="empty">{t.empty}</div>}</section>
 <section className="history"><div className="section-heading"><div><div className="section-kicker">{t.history}</div><h2>{t.history}</h2></div></div><div className="table-wrap"><table><thead><tr><th>{t.last}</th><th>{t.mode}</th><th>{t.scanned}</th><th>{t.verified}</th><th>{t.skipped}</th><th>{t.failed}</th></tr></thead><tbody>{runs.map(item=><tr key={item.id}><td>{date(item.StartedAt)}</td><td><code>{item.Mode}</code></td><td>{item.Scanned}</td><td>{item.Verified}</td><td>{item.Skipped}</td><td className={item.Failed?"bad":""}>{item.Failed}</td></tr>)}</tbody></table></div></section>
 {selected.length>0&&<aside className="action-bar"><div><strong>{selected.length} {t.selected}</strong><span>{t.warning}</span></div><div>{token&&<button className="quiet"onClick={()=>setToken("")}>{t.cancel}</button>}<button className={token?"danger":"primary"}onClick={()=>void(token?run():preview())}>{token?t.confirm:t.prepare}</button></div></aside>}</main>
}
function AccountRow({account,selected,onSelect,labels}:{account:Account;selected:boolean;onSelect:(checked:boolean)=>void;labels:typeof copy.pt|typeof copy.en}){const status=account.Snapshot.eligible?labels.eligible:account.Snapshot.primary.presence==="present"?labels.active:labels.unknown;const reason=labels.reason[account.Snapshot.reason as keyof typeof labels.reason]??account.Snapshot.reason.replaceAll("_"," ");return <article className="account"><div className="account-main"><input aria-label={identity(account)}type="checkbox"checked={selected}disabled={!account.Snapshot.eligible}onChange={event=>onSelect(event.target.checked)}/><div className="avatar">{identity(account).slice(0,2).toUpperCase()}</div><div className="identity"><strong>{identity(account)}</strong><span>{account.Plan||"—"} · {reason}</span></div><span className={`status ${account.Snapshot.eligible?"eligible":"active"}`}>{status}</span></div><div className="window-grid"><QuotaRail title={labels.primary}window={account.Snapshot.primary}labels={labels}/><QuotaRail title={labels.secondary}window={account.Snapshot.secondary}labels={labels}/></div></article>}
function QuotaRail({title,window,labels}:{title:string;window:QuotaWindow;labels:typeof copy.pt|typeof copy.en}){if(window.presence!=="present")return <div className="quota-rail absent"><div><strong>{title}</strong><span>{labels.unknown}</span></div><div className="rail"/></div>;const remaining=Math.max(0,Math.min(100,100-window.used_percent));return <div className="quota-rail"><div><strong>{title}</strong><span>{remaining.toFixed(0)}% {labels.remaining} · {labels.reset} {duration(window.reset_after_seconds)}</span></div><div className="rail"><i style={{width:`${remaining}%`}}/></div></div>}
function Summary({label,value,detail,status}:{label:string;value:string;detail?:string;status?:"good"|"neutral"}){return <div><span>{label}</span><strong className={status??""}>{value}</strong>{detail&&<small>{detail}</small>}</div>}
function Login({title,subtitle,label,action,value,onChange,onSubmit}:{title:string;subtitle:string;label:string;action:string;value:string;onChange:(value:string)=>void;onSubmit:()=>void}){return <main className="login"><section><div className="login-mark">CQ</div><div className="crumb">CLIProxyAPI / {title}</div><h1>{title}</h1><p>{subtitle}</p><label>{label}<input autoFocus type="password"autoComplete="off"value={value}onChange={event=>onChange(event.target.value)}onKeyDown={event=>event.key==="Enter"&&onSubmit()}/></label><button className="primary full"onClick={onSubmit}>{action}</button></section></main>}
function SessionState({title,message,action,onRetry}:{title:string;message:string;action:string;onRetry:()=>void}){return <main className="login"><section><div className="login-mark">CQ</div><div className="crumb">CLIProxyAPI / {title}</div><h1>{title}</h1><p>{message}</p>{action&&<button className="primary full"onClick={onRetry}>{action}</button>}</section></main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
